In [1]:
import pandas as pd
df =pd.read_csv("retail_store_sales.csv")
df.head(25)

,Transaction ID,Customer ID,Category,Item,Price Per Unit,Quantity,Total Spent,Payment Method,Location,Transaction Date,Discount Applied
0,TXN_6867343,CUST_09,Patisserie,Item_10_PAT,18.5,10.0,185.0,Digital Wallet,Online,2024-04-08,True
1,TXN_3731986,CUST_22,Milk Products,Item_17_MILK,29.0,9.0,261.0,Digital Wallet,Online,2023-07-23,True
2,TXN_9303719,CUST_02,Butchers,Item_12_BUT,21.5,2.0,43.0,Credit Card,Online,2022-10-05,False
3,TXN_9458126,CUST_06,Beverages,Item_16_BEV,27.5,9.0,247.5,Credit Card,Online,2022-05-07,NaN
4,TXN_4575373,CUST_05,Food,Item_6_FOOD,12.5,7.0,87.5,Digital Wallet,Online,2022-10-02,False
5,TXN_7482416,CUST_09,Patisserie,NaN,NaN,10.0,200.0,Credit Card,Online,2023-11-30,NaN
6,TXN_3652209,CUST_07,Food,Item_1_FOOD,5.0,8.0,40.0,Credit Card,In-store,2023-06-10,True
7,TXN_1372952,CUST_21,Furniture,NaN,33.5,NaN,NaN,Digital Wallet,In-store,2024-04-02,True
8,TXN_9728486,CUST_23,Furniture,Item_16_FUR,27.5,1.0,27.5,Credit Card,In-store,2023-04-26,False
9,TXN_2722661,CUST_25,Butchers,Item_22_BUT,36.5,3.0,109.5,Cash,Online,2024-03-14,False
10,TXN_8776416,CUST_22,Butchers,Item_3_BUT,8.0,9.0,72.0,Cash,In-store,2024-12-14,True
11,TXN_5422631,CUST_09,Milk Products,NaN,NaN,8.0,52.0,Digital Wallet,In-store,2025-01-12,True
12,TXN_5874772,CUST_23,Food,Item_2_FOOD,6.5,7.0,45.5,Cash,Online,2023-09-09,True
13,TXN_4413070,CUST_14,Patisserie,Item_24_PAT,39.5,6.0,237.0,Digital Wallet,In-store,2022-05-20,False
14,TXN_2490363,CUST_09,Milk Products,Item_16_MILK,27.5,2.0,55.0,Digital Wallet,Online,2022-05-22,NaN
15,TXN_1809665,CUST_14,Beverages,NaN,24.5,NaN,NaN,Credit Card,In-store,2022-05-11,NaN
16,TXN_7563311,CUST_23,Patisserie,Item_17_PAT,29.0,8.0,232.0,Cash,Online,2024-11-16,True
17,TXN_9634894,CUST_15,Milk Products,NaN,NaN,10.0,275.0,Digital Wallet,Online,2022-04-17,NaN
18,TXN_4396807,CUST_17,Electric household essentials,Item_13_EHE,23.0,1.0,23.0,Digital Wallet,In-store,2022-02-07,False
19,TXN_4206593,CUST_01,Furniture,NaN,35.0,NaN,NaN,Digital Wallet,Online,2025-01-13,False
20,TXN_9939063,CUST_14,Beverages,Item_7_BEV,14.0,9.0,126.0,Digital Wallet,In-store,2024-01-14,NaN
21,TXN_8685338,CUST_15,Milk Products,NaN,NaN,3.0,105.0,Credit Card,In-store,2023-10-29,NaN
22,TXN_6547964,CUST_10,Electric household essentials,Item_4_EHE,9.5,7.0,66.5,Cash,In-store,2022-08-15,NaN
23,TXN_3314099,CUST_04,Food,Item_10_FOOD,18.5,1.0,18.5,Cash,Online,2023-09-30,False
24,TXN_9980736,CUST_13,Furniture,Item_14_FUR,24.5,2.0,49.0,Cash,Online,2023-08-29,False

In [2]:
df["Price Per Unit"]=df["Price Per Unit"].fillna(df["Total Spent"]/df["Quantity"])

In [22]:
df[df["Category"]=="Electric household essentials"][["Item","Price Per Unit"]].sort_values("Item")

      Item  Price Per Unit
18     EHE            23.0
8507   EHE            23.0
8494   EHE            15.5
8488   EHE            38.0
8486   EHE            17.0
...    ...             ...
12365  NaN            26.0
12455  NaN            33.5
12457  NaN            21.5
12519  NaN            35.0
12564  NaN            29.0

[1591 rows x 2 columns]

In [45]:
df.head(40)

,Transaction ID,Customer ID,Category,Item,Price Per Unit,Quantity,Total Spent,Payment Method,Location,Transaction Date,Discount Applied
0,TXN_6867343,CUST_09,Patisserie,PAT,18.5,10.0,185.0,Digital Wallet,Online,2024-04-08,True
1,TXN_3731986,CUST_22,Milk Products,MILK,29.0,9.0,261.0,Digital Wallet,Online,2023-07-23,True
2,TXN_9303719,CUST_02,Butchers,BUT,21.5,2.0,43.0,Credit Card,Online,2022-10-05,False
3,TXN_9458126,CUST_06,Beverages,BEV,27.5,9.0,247.5,Credit Card,Online,2022-05-07,Unknown
4,TXN_4575373,CUST_05,Food,FOOD,12.5,7.0,87.5,Digital Wallet,Online,2022-10-02,False
5,TXN_7482416,CUST_09,Patisserie,PAT,20.0,10.0,200.0,Credit Card,Online,2023-11-30,Unknown
6,TXN_3652209,CUST_07,Food,FOOD,5.0,8.0,40.0,Credit Card,In-store,2023-06-10,True
7,TXN_1372952,CUST_21,Furniture,FUR,33.5,6.0,108.5,Digital Wallet,In-store,2024-04-02,True
8,TXN_9728486,CUST_23,Furniture,FUR,27.5,1.0,27.5,Credit Card,In-store,2023-04-26,False
9,TXN_2722661,CUST_25,Butchers,BUT,36.5,3.0,109.5,Cash,Online,2024-03-14,False
10,TXN_8776416,CUST_22,Butchers,BUT,8.0,9.0,72.0,Cash,In-store,2024-12-14,True
11,TXN_5422631,CUST_09,Milk Products,MILK,6.5,8.0,52.0,Digital Wallet,In-store,2025-01-12,True
12,TXN_5874772,CUST_23,Food,FOOD,6.5,7.0,45.5,Cash,Online,2023-09-09,True
13,TXN_4413070,CUST_14,Patisserie,PAT,39.5,6.0,237.0,Digital Wallet,In-store,2022-05-20,False
14,TXN_2490363,CUST_09,Milk Products,MILK,27.5,2.0,55.0,Digital Wallet,Online,2022-05-22,Unknown
15,TXN_1809665,CUST_14,Beverages,BEV,24.5,6.0,108.5,Credit Card,In-store,2022-05-11,Unknown
16,TXN_7563311,CUST_23,Patisserie,PAT,29.0,8.0,232.0,Cash,Online,2024-11-16,True
17,TXN_9634894,CUST_15,Milk Products,MILK,27.5,10.0,275.0,Digital Wallet,Online,2022-04-17,Unknown
18,TXN_4396807,CUST_17,Electric household essentials,EHE,23.0,1.0,23.0,Digital Wallet,In-store,2022-02-07,False
19,TXN_4206593,CUST_01,Furniture,FUR,35.0,6.0,108.5,Digital Wallet,Online,2025-01-13,False
20,TXN_9939063,CUST_14,Beverages,BEV,14.0,9.0,126.0,Digital Wallet,In-store,2024-01-14,Unknown
21,TXN_8685338,CUST_15,Milk Products,MILK,35.0,3.0,105.0,Credit Card,In-store,2023-10-29,Unknown
22,TXN_6547964,CUST_10,Electric household essentials,EHE,9.5,7.0,66.5,Cash,In-store,2022-08-15,Unknown
23,TXN_3314099,CUST_04,Food,FOOD,18.5,1.0,18.5,Cash,Online,2023-09-30,False
24,TXN_9980736,CUST_13,Furniture,FUR,24.5,2.0,49.0,Cash,Online,2023-08-29,False
25,TXN_3481599,CUST_05,Furniture,FUR,39.5,6.0,108.5,Cash,Online,2022-09-08,False
26,TXN_9057609,CUST_18,Butchers,BUT,33.5,4.0,134.0,Credit Card,In-store,2022-03-16,True
27,TXN_1599706,CUST_14,Furniture,FUR,41.0,10.0,410.0,Credit Card,In-store,2024-03-24,True
28,TXN_1598860,CUST_08,Food,FOOD,24.5,10.0,245.0,Cash,In-store,2022-10-23,True
29,TXN_7138501,CUST_18,Patisserie,PAT,36.5,5.0,182.5,Credit Card,In-store,2022-03-10,False
30,TXN_5444504,CUST_05,Food,FOOD,20.0,10.0,200.0,Digital Wallet,Online,2022-04-26,False
31,TXN_4353295,CUST_22,Patisserie,PAT,12.5,8.0,100.0,Credit Card,Online,2022-04-05,True
32,TXN_1543244,CUST_20,Food,FOOD,24.5,8.0,196.0,Credit Card,Online,2024-10-25,True
33,TXN_1494700,CUST_12,Electric household essentials,EHE,35.0,9.0,315.0,Credit Card,In-store,2024-03-07,Unknown
34,TXN_1621497,CUST_06,Patisserie,PAT,23.0,6.0,108.5,Cash,In-store,2023-02-18,Unknown
35,TXN_6398436,CUST_15,Beverages,BEV,41.0,7.0,287.0,Credit Card,In-store,2024-06-03,True
36,TXN_9065245,CUST_02,Food,FOOD,38.0,2.0,76.0,Digital Wallet,In-store,2024-03-10,False
37,TXN_6963438,CUST_11,Furniture,FUR,18.5,5.0,92.5,Credit Card,Online,2024-04-23,True
38,TXN_8312797,CUST_14,Beverages,BEV,20.0,5.0,100.0,Digital Wallet,Online,2022-06-03,Unknown
39,TXN_5836005,CUST_19,Butchers,BUT,38.0,5.0,190.0,Credit Card,In-store,2024-10-19,False

In [40]:
category_to_item ={
    "Milk Products": "milk",
    "Patisserie":"PAT",
    "Butchers": "BUT",
    "Beverages": "BEV",
    "Furniture": "FUR",
    "Food": "FOOD",
    "Electric household essentials": "EHE",
    "Computers and electric accessories":"CEA"
}

In [43]:
df["Item"]=df["Item"].fillna(df["Category"].map(category_to_item))

In [47]:
df["Price Per Unit"].isna().sum()

np.int64(0)

In [6]:
df[["Quantity","Total Spent"]]=df[["Quantity","Total Spent"]].fillna(df[["Quantity","Total Spent"]].median())

In [13]:
mask = (
    df["Quantity"].isna() &
    df["Price Per Unit"].notna()&
    df["Total Spent"].notna()
)

In [61]:
(df["Quantity"].isna()&df["Total Spent"].isna()).sum()

np.int64(604)

In [14]:
df.loc[mask,["Quantity","Price Per Unit","Total Spent"]].head(20)

Empty DataFrame
Columns: [Quantity, Price Per Unit, Total Spent]
Index: []

In [10]:
df["Price Per Unit"]=df["Price Per Unit"].fillna(df.groupby("Category")["Price Per Unit"].transform("median"))

In [46]:
df.isnull().sum()

Transaction ID      0
Customer ID         0
Category            0
Item                0
Price Per Unit      0
Quantity            0
Total Spent         0
Payment Method      0
Location            0
Transaction Date    0
Discount Applied    0
dtype: int64

In [38]:
df.loc[df["Item"].isna(),["Category",'Item']]["Category"].value_counts(dropna=False)

Category
Food    162
Name: count, dtype: int64

In [32]:
df["Item"]=df["Item"].replace("milk","MILK")

In [16]:
df["Discount Applied"]=df["Discount Applied"].fillna("Unknown")

In [39]:
df["Category"].value_counts()

Category
Furniture                             1591
Electric household essentials         1591
Food                                  1588
Milk Products                         1584
Butchers                              1568
Beverages                             1567
Computers and electric accessories    1558
Patisserie                            1528
Name: count, dtype: int64

In [36]:
df[df["Item"].isna()]

,Transaction ID,Customer ID,Category,Item,Price Per Unit,Quantity,Total Spent,Payment Method,Location,Transaction Date,Discount Applied
32,TXN_1543244,CUST_20,Food,NaN,24.5,8.0,196.0,Credit Card,Online,2024-10-25,True
232,TXN_1811555,CUST_15,Food,NaN,30.5,6.0,108.5,Cash,Online,2023-07-31,Unknown
259,TXN_9130896,CUST_03,Food,NaN,20.0,6.0,108.5,Digital Wallet,In-store,2022-05-17,Unknown
333,TXN_4351153,CUST_21,Food,NaN,17.0,6.0,108.5,Cash,In-store,2024-12-07,False
340,TXN_2496138,CUST_22,Food,NaN,11.0,6.0,108.5,Cash,Online,2023-10-04,Unknown
...,...,...,...,...,...,...,...,...,...,...,...
12313,TXN_3525275,CUST_21,Food,NaN,20.0,1.0,20.0,Digital Wallet,Online,2024-03-16,False
12369,TXN_2414883,CUST_04,Food,NaN,41.0,6.0,108.5,Cash,In-store,2022-02-01,Unknown
12396,TXN_1720372,CUST_20,Food,NaN,11.0,6.0,108.5,Credit Card,In-store,2023-10-23,True
12511,TXN_5715500,CUST_17,Food,NaN,33.5,3.0,100.5,Digital Wallet,Online,2024-06-05,False
12527,TXN_1069238,CUST_23,Food,NaN,5.0,6.0,108.5,Digital Wallet,In-store,2022-08-13,False

In [18]:
df["Item"].value_counts()

Item
FUR     1460
EHE     1437
BEV     1427
FOOD    1426
MILK    1425
BUT     1421
CEA     1397
PAT     1369
Name: count, dtype: int64

In [19]:
df[["Category","Item"]].drop_duplicates().sort_values("Category")

                               Category  Item
3                             Beverages   BEV
15                            Beverages   NaN
2                              Butchers   BUT
127                            Butchers   NaN
46   Computers and electric accessories   CEA
112  Computers and electric accessories   NaN
18        Electric household essentials   EHE
234       Electric household essentials   NaN
4                                  Food  FOOD
32                                 Food   NaN
7                             Furniture   NaN
8                             Furniture   FUR
1                         Milk Products  MILK
11                        Milk Products   NaN
0                            Patisserie   PAT
5                            Patisserie   NaN

In [10]:
df["Discount Applied"].value_counts()

Discount Applied
True       4219
Unknown    4199
False      4157
Name: count, dtype: int64

In [3]:
df.groupby("Item")["Category"].nunique()

NameError: name 'df' is not defined

In [2]:
df["Payment Method"].unique()

<StringArray>
['Digital Wallet', 'Credit Card', 'Cash']
Length: 3, dtype: str

In [11]:
df["Item"]=df["Item"].str.extract(r"_([A-Za-z]+)$")

In [1]:
import pandas as pd
df= pd.read_csv("retail_cleaned.csv")

In [47]:
df.to_csv("retail_cleaned.csv",index=False)

In [2]:
from sqlalchemy import create_engine
engine = create_engine(
    "mysql+pymysql://root:1234@127.0.0.1:3306/suvi_db"
)

In [3]:
df.to_sql(
    "retail_data",
    con=engine,
    if_exists="replace",
    index=False
)

12575